# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lnr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendpoked', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friendsfriend', to='lnr.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usersfriend', to='lnr.User')),
            ],
        ),
    ]
